table Sales
	lineageTag: a1a1a1a1-0001-0002-0003-000000000001

	measure 'Total Revenue' = SUM(Sales[Revenue])
		formatString: \$#,0
		lineageTag: a1a1a1a1-0001-0002-0003-000000000011

	measure 'Total Units' = SUM(Sales[Units])
		formatString: #,0
		lineageTag: a1a1a1a1-0001-0002-0003-000000000012

	column Product
		dataType: string
		lineageTag: a1a1a1a1-0001-0002-0003-000000000021
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a1a1a1a1-0001-0002-0003-000000000022
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: int64
		formatString: #,0
		lineageTag: a1a1a1a1-0001-0002-0003-000000000023
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: int64
		formatString: \$#,0
		lineageTag: a1a1a1a1-0001-0002-0003-000000000024
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    // Dados ficticios espelhando data/sales.csv (inline = self-contained, atualiza em qualquer lugar, inclusive no Fabric)
				    Source = Table.FromRows(
				        {
				            {"Alpha", "North", 120, 2400},
				            {"Alpha", "South", 80, 1600},
				            {"Beta", "North", 200, 5000},
				            {"Beta", "South", 150, 3750},
				            {"Gamma", "North", 90, 2700},
				            {"Gamma", "South", 60, 1800}
				        },
				        {"Product", "Region", "Units", "Revenue"}
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(Source, {{"Product", type text}, {"Region", type text}, {"Units", Int64.Type}, {"Revenue", Int64.Type}})
				in
				    #"Changed Type"
